env: dev
log:
  format: syslog
  level: 3

http:
    - tag: main
      addr: 127.0.0.2:20000
    - tag: pki
      addr: 127.0.0.3:20000

pgsql:
    - tags: master,slave
      host: 127.0.0.1
      port: 5432
      schema: postgres
      user: postgres
      password: postgres
      sslmode: false
      app_name: casper_app
      charset: UTF8
      maxidleconn: 5
      maxopenconn: 5
      maxconnttl: 50s
      timeout: 5s
      other_params: ""

db_migrate:
    - tags: master
      dialect: pgsql
      dir: /var/lib/casper/migrations

certs:
  - root_ca_chain:
      - /var/lib/casper/root.crt
    issuing_ca_cert: /var/lib/casper/intermediate.crt
    issuing_ca_key: /var/lib/casper/intermediate.key
    domains:
      - localhost
      - example.com
    default_expire_days: 90
    issuing_certificate_urls:
      - http://pki.domain/icu/ca-l2.crt
    ocsp_server_urls:
      - http://pki.domain/ocsp/ca-l2
    crl_distribution_point_urls:
      - http://pki.domain/crl/ca-l2.crl
    certificate_policies_urls:
      - http://pki.domain/cps/ca-l2.html
